version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  test-and-analyze:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: npm

      - run:
          name: Run tests (if any)
          command: echo "No tests yet"

      - sonarcloud/scan:
          project_key: Kgatliso68_secure-payments-portal
          organization: kgatliso68

workflows:
  main:
    jobs:
      - test-and-analyze:
          context: SonarCloud
